theme: jekyll-theme-hacker
title : Parth Parekh's Personal Website
description : I am about to pubish creative content on Artificial Intelligence, Machine Learning, Information Security, etc. For, project also you may contact.
